MYSEED: 0
alpha: 128
batch_size: 8
bins: 100
crop_size: !!python/tuple [480, 480]
cudaid: '0'
dataset: glas
epoch_start_erasing: 1
extension: !!python/tuple [jpeg, JPEG]
floating: 3
fold: 0
fold_folder: ./folds
height_tag: 50
img_extension: bmp
max_epochs: 400
model:
  alpha: 0.0
  dropout: 0.75
  kmax: 0.09
  kmin: 0.09
  modalities: 5
  name: resnet101
  num_classes: 2
  num_masks: 1
  pretrained: true
  scale: &id001 !!python/tuple [0.5, 0.5]
  sigma: 0.5
  smooth_out: false
  w: 8
name_classes: {benign: 0, malignant: 1}
nbr_classes: 2
nbr_times_erase: 4
normalize: true
num_workers: 8
optimizer:
  dampening: 0.0
  lr: 0.001
  lr_scheduler: {gamma: 0.1, last_epoch: -1, min_lr: 1.0e-07, name: mystep, step_size: 40}
  momentum: 0.9
  name: sgd
  nesterov: true
  weight_decay: 1.0e-05
pad_eval: false
padding_mode: reflect
padding_size: *id001
preload: true
rangeh: !!python/tuple [0, 1]
resize: null
show_hists: true
sigma_erase: 10.0
split: 0
up_scale_small_dim_to: null
use_tags: true
yaml: glas.yaml
